---
title: "Censos hist칩ricos (1842-2011): obtenci칩n de los datos"
# subtitle: | 
#   Utilizando datos de los censos hist칩ricos (1842-2011) y del Padr칩n, se muestra el ranking de ciudades espa침olas m치s pobladas.
date: 2022-07-12
categories: [datos INE, Censos hist칩ricos, poblaci칩n, municipios, web scraping]
bibliography: references.bib
nocite: |
  @*
---

Se describe el proceso de obtenci칩n y procesado de los datos de los censos hist칩ricos de poblaci칩n en Espa침a (1842-2011) que ofrece el INE.

<br>

## Introducci칩n

A todos nos gusta saber cuantos habitantes tiene nuestro pueblo; y como nos dice [el conde Draco](https://www.youtube.com/watch?v=KZmLI7eYjmw){target="_blank"} esto se hace en los censos. Un **censo** de poblaci칩n es una operaci칩n estad칤stica cuyo principal objetivo es hacer un recuento de la poblaci칩n, as칤 como de sus principales caracter칤sticas sociales y demogr치ficas. En este post describo el proceso que tuve que hacer para **obtener y procesar los datos de los censos hist칩ricos de poblaci칩n** en Espa침a que ofrece el INE en su web. En posteriores posts se supone que los usar칠 para hacer algunas visualizaciones y an치lisis, como por ejemplo, la evoluci칩n del ranking de capitales de provincia m치s pobladas o la evoluci칩n de la importancia (en t칠rminos de poblaci칩n) de las capitales provinciales en su propia provincia; adem치s, seguro que utilizo estos datos en mi curso de introducci칩n a R en la UV. Son datos chulos y no exigen mucha carga mental para analizarlos.

::: column-margin
**Objetivo:** Obtener los datos de los censos hist칩ricos (1842-2011) ofrecidos por el INE.
:::

## Obtenci칩n de los datos (Web scraping)

El INE ofrece [aqu칤](https://www.ine.es/inebaseweb/libros.do?tntp=71807#){target="_blank"} acceso a los censos realizados en Espa침a durante el periodo 1857-1970[^1]. El acceso es a trav칠s de documentos pdf, de forma que, para poder recopilar los datos all칤 contenidos se tendr칤an que procesar a mano (no way!!) o por tecnolog칤as OCR (hay que saber mucho y ser un poco orfebre!!)[^2]; as칤 que me olvid칠 de los pdf's y me fui al segundo punto de acceso a los datos, concretamente [aqu칤](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176998&menu=resultados&idp=1254735572981){target="_blank"} para **obtener los datos por Web scraping**. En este segundo punto de acceso se ofrecen datos de los censos **para el periodo 1842-2011**.^[Para censos anteriores puede verse [esta publicaci칩n](https://www.ine.es/explica/docs/historia_censos.pdf) del INE]

[^1]: [En esta publicaci칩n del INE](https://www.ine.es/explica/docs/historia_censos.pdf){target="_blank"} puede encontrase una peque침a rese침a de los principales censos hist칩ricos hechos en Espa침a

[^2]: La verdad es que prob칠 los paquetes `tesseract` y `tabulizer` y no lo hac칤an mal, pero hac칤a falta mucho m치s trabajo para llegar a algo medio decente. Intent칠 probar el paquete `daiR` que da acceso a la Google Cloud Document AI API, que se supone que es la ca침a para extraer texto y tablas de pdf's, **PERO** es un servicio de pago. No parec칤a muy caro, pero no lo prob칠.

::: column-margin
Obtendremos los datos mediante **web scraping**
:::

Esta segunda forma de obtener los datos, por Web scraping, tampoco es que sea extremadamente f치cil ya que el INE, ofrece un buscador en el que puedes hacer consultas para un s칩lo municipio (o provincia), de forma que, habr칤a que hacer cerca de 12.000 consultas a mano para descargarse los datos de poblaci칩n de todos los municipios espa침oles que han existido desde 1842. Factible, pero mejor si se hacen las peticiones de datos mediante un proceso automatizado y descargas los datos mediante Web scraping. De esta forma se recogen los datos en menos de una hora.

Ser칤a as칤 de f치cil si el INE ofreciese un listado de c칩digos para los municipios que han existido a lo largo de la historia en Espa침a para as칤 poder hacer las consultas, pero esto no es as칤. El INE ofrece un listado de c칩digos municipales [aqu칤](https://www.ine.es/daco/daco42/codmun/codmunmapa.htm){target="_blank"} **pero s칩lo** para los municipios "actuales", as칤 que el proceso para obtener los datos tuvo varias etapas:

::: column-margin
El proceso de scraping tuvo **varias etapas**
:::

-   De los datos de la revisi칩n del padr칩n municipal extraje los c칩digos de los municipios que han existido en Espa침a en el periodo 1996 y 1998-2021: un total de 8.120 c칩digos municipales. Con estos c칩digos hice peticiones a la web del INE para generar las tablas con sus datos y poder hacer Web scraping para extraer los datos de poblaci칩n de los censos hist칩ricos de esos 8.120 municipios.

-   En las tablas de cada municipio, adem치s de los datos de poblaci칩n[^3], se ofrece una serie de notas con informaci칩n sobre fen칩menos como el cambio de nombre de los municipios y sus alteraciones municipales[^4]. Al **procesar estas anotaciones**, buscando conjuntos de d칤gitos de 5 o 6 d칤gitos, se consiguieron recuperar 2.924 c칩digos municipales adicionales. Son c칩digos que no aparecen en los datos del Padr칩n porque estos municipios se extinguieron antes de 1998.

-   Con los c칩digos de estos 2.924 "nuevos" municipios se hicieron nuevas peticiones al INE, de las cuales surgieron nuevas notas de alteraciones municipales, que a su vez proporcionaron nuevos c칩digos municipales.

-   Se tuvo que **repetir este proceso 5 veces** hasta que de las notas de la 칰ltima vuelta no surgieron nuevos c칩digos municipales. En total hab칤a escrapeado un total de 11.882 municipios: 8.120 en la primera vuelta, 2.924 en la segunda, 767, 69, y finalmente 2 nuevos municipios en la quinta y 칰ltima ronda.

[^3]: Concretamente se ofrece la poblaci칩n de derecho, la poblaci칩n de hecho y el n칰mero de hogares.

[^4]: Por ejemplo si son absorbidos por otro municipio; como por ejemplo Vallecas, que exist칤a como municipio independiente en el censo de 1940 pero pas칩 a estar integrado en el municipio de Madrid en el censo de 1950.

Parec칤a que todo estaba bien, que hab칤a conseguido localizar todos los municipios existentes en la web del INE, pero ... no me fiaba ya que del procesado de texto siempre suele haber errores, as칤 que gracias a que conozco a Francisco J. Goerlich, seguramente la persona que m치s sabe de estos temas[^5], consegu칤 detectar que **me faltaban a칰n 28 municipios por encontrar**. El fallo no fue causado por mi proceso de scraping sino por "fallos" en las anotaciones en las tablas del INE.

[^5]: Y de muchos otros (temas) 游뗵.

::: column-margin
Tras las 5 vueltas del scraping se recopilaron datos de **11.882 c칩digos municipales** ...
:::

De los 28 municipios que el scraping no detect칩, en 4 de ellos el motivo fue que hab칤a fallos[^7] en las notas que hubieran permitido detectarlos. En los restantes 24 municipios que no se detectaron, la raz칩n fue similar: son municipios que solo aparecen en el primer censo que registra el INE, el de 1842, y en su nota al pie solo pone algo como "Este municipio que aparece en el Censo de 1842, ..., no se le localiza en el Censo de 1857", pero no dice si se integraron en otro municipio o se volatilizaron, de forma que era imposible detectarlos mediante el proceso de Web scraping. 

[^7]: Los 4 municipios son San Quirce de Riopisuerga (09342), G치tova (12066), Rivas de Tereso (26504) y Los Hueros (28511). El fallo consisti칩 en que su c칩digo municipal estaba incompleto en la nota que hubiese permitido detectarlos; concretamente su c칩digo municipal solo ten칤a 3 d칤gitos en lugar de los 5 habituales.

::: column-margin
... pero a칰n faltaban 28 municipios.
:::

Tras este proceso, ten칤a los datos de los **11.910 municipios** que han existido en Espa침a, a juzgar por la informaci칩n que aparece en los censos hist칩ricos del INE 1842-2011[^8].

[^8]: Se침alar que existen casos digamos "extra침os", como por ejemplo el municipio de Gatova que cambi칩 su c칩digo de 12066 a 46092 al incorporarse a la provincia de Valencia, desde la de Castell칩n, en el censo de 2001. 쯉on municipios diferentes? Bueno, podemos pensar que s칤, ya que tienen c칩digos municipales diferentes.

::: column-margin
Al final se obtuvieron datos de 11.910 municipios.
:::

## 쯈u칠 variables hay en los datos?

Los datos del INE contienen, tal y como se explica [aqu칤](https://www.ine.es/intercensal/){target="_blank"}, una tabla para cada uno de los municipios que han sido censados en Espa침a desde 1842. Para cada municipio se recogen **3 variables**: poblaci칩n de hecho, poblaci칩n de derecho y n칰mero de hogares. Adem치s se recogen, en las notas al pie de la tabla, determinadas alteraciones municipales. Como ejemplo, [aqu칤](https://www.ine.es/intercensal/intercensal.do?search=1&error1=Debe+introducir+un+nombre+de+municipio.&error2=Debe+introducir+al+menos+3+caracteres.&cmbTipoBusq=0&textoMunicipio=Pancrudo&btnBuscarDenom=Consultar+selecci%C3%B3n){target="_blank"} puedes ver la tabla para Pancrudo que, como se aprecia en las notas, incorpor칩 a Portalrubio en el censo de 1981.

::: column-margin
**3 variables**: hogares, poblaci칩n de hecho y poblaci칩n de derecho.
:::

En la tabla se aprecia que hay **dos variables de poblaci칩n**: la de hecho y la de derecho. Para mis an치lisis utilizar칠 la **poblaci칩n de derecho**, salvo en los censos de 1857 y 1860 en los que como no hay registro para la poblaci칩n de derecho, la sustituir칠 por la de hecho, para as칤 tener una serie completa de poblaci칩n para todos los censos del periodo 1842-2011. Es posible que en algunos an치lisis a침ada tambi칠n los datos del Padr칩n (1998-2021).

::: column-margin
Usare la **poblaci칩n de derecho**, salvo cuando esta no est칠 disponible.
:::

## 쮺ifras oficiales de poblaci칩n?

Voy a utilizar estos datos para hacer algunos an치lisis y visualizaciones, as칤 que cabe preguntarse si son datos "oficiales" de poblaci칩n y si est치n libres de errores. En principio los datos que he obtenido por web scraping de la web del INE deber칤an ser las "cifras oficiales" de poblaci칩n de los municipios espa침oles, pero en [Goerlich y otros (2015)](https://www.fbbva.es/publicaciones/cambios-en-la-estructura-y-localizacion-de-la-poblacion-una-vision-de-largo-plazo-1842-2011/){target="_blank"} se침alan, concretamente en los apartados 2.2.6, 2.2.7 y 2.2.8, diversos errores de transcripci칩n[^9].

[^9]: Esos errores de transcripci칩n se describen en detalle en los apartados 2.2.6, 2.2.7 y 2.2.8 de [este libro](https://www.fbbva.es/publicaciones/cambios-en-la-estructura-y-localizacion-de-la-poblacion-una-vision-de-largo-plazo-1842-2011/){target="_blank"}

::: column-margin
[Goerlich y otros (2015)](https://www.fbbva.es/publicaciones/cambios-en-la-estructura-y-localizacion-de-la-poblacion-una-vision-de-largo-plazo-1842-2011/){target="_blank"} detectaron errores de transcripci칩n.
:::

Sin embargo, esos errores detectados pr치cticamente no afectan a los an치lisis y visualizaciones que har칠 en el blog. En concreto, los errores detectados que afectan a las capitales de provincia son menores, solo detect치ndose diferencias importantes en Ceuta, Melilla y Madrid en el censo de 1991[^10], as칤 que para los an치lisis que voy a hacer en el blog doy por buenos los datos que figuran [aqu칤](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736176998&menu=resultados&idp=1254735572981){target="_blank"} en la web del INE.

[^10]: Como ejemplo, se침alar que, en el caso de Madrid, la poblaci칩n que figura en la web del INE para el censo de 1991 es de 2.909.792, mientras que en el Censo original es de 3.010.492. Este error supone un 3,46%.

::: column-margin
Esos errores afectar칤an m칤nimamente a los resultados mostrados en el blog.
:::

Mi objetivo no es hacer un art칤culo cient칤fico, sino tan solo, hacer algunos an치lisis y visualizaciones que describan, a grandes rasgos, la evoluci칩n hist칩rica de la poblaci칩n municipal en Espa침a, para usarlos en mis clases, as칤 que yo los voy a dar por buenos.

Tampoco voy a tratar de corregir la poblaci칩n por las alteraciones municipales que hayan ocurrido; es decir no trato de obtener series homog칠neas de poblaci칩n, entre otras cosas porque ya lo ha hecho Paco Goerlich!!

Supongo que un historiador podr치 decir mucho sobre la validez, cambios de criterios y dem치s infortunios acaecidos a lo largo de los distintos censos. Yo aqu칤 voy a dar por buenos los datos: son del INE!! 游땒

Bueno pues ya he dejado medio descrito el proceso de obtenci칩n de los datos as칤 que cierro el post: ya los usar칠 en futuros post.

## 쯈u칠 voy a hacer con los datos?

La verdad es que los datos cuesta un poquito acceder a ellos, menos mal que ven칤a de un proyecto en el que hab칤a escrapeado los resultados de atletismo de la IAAF, que despu칠s me hab칤a llevado a escrapear datos de premios literarios, vamos que estaba entrenado en scraping y en una tarde lo ten칤a (casi) hecho, pero ... y ... y al final ten칤a los datos!!! 游 Demasiado jaleo para lo que voy a hacer[^11] pero, ...

[^11]: Adem치s, seguro que lo que haga ya estar치 hecho seguramente en [este libro](https://www.fbbva.es/publicaciones/cambios-en-la-estructura-y-localizacion-de-la-poblacion-una-vision-de-largo-plazo-1842-2011/){target="_blank"}. Tiene 354 p치ginas!!!! No voy a mirar mucho por si acaso!!

OK, vale, pero 쯤u칠 vas a hacer? Pues a칰n no lo s칠 del todo, pero seguro que juego con ellos para satisfacer mi curiosidad y preparar posibles ejercicios para el pr칩ximo curso.

::: column-margin
Veremos que hago con estos datos ...
:::

<br><br>

## Referencias

(Algunos art칤culos que hablan de la evoluci칩n hist칩rica de la poblaci칩n y/o de los censos hist칩ricos)

::: {#refs}
:::
